#!/bin/sh

[ "${ACTION}" = "released" -o "${ACTION}" = "timeout" ] || exit 21

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

# factory reset
if [ "$SEEN" -gt 20 ]
then
	[ -f /tmp/.factory_reset ] && return
	echo timer > /sys/class/leds/mica\:wifi/trigger
	echo 100 > /sys/class/leds/mica\:wifi/delay_on
	echo 100 > /sys/class/leds/mica\:wifi/delay_off
	touch /tmp/.factory_reset
	echo "FACTORY RESET" > /dev/console
	jffs2reset -y
	sync
	reboot
# wifi reset (back to ap mode)
elif [ "$SEEN" -gt 5 ]
then
	mica_mode="$(uci get wireless.radio0.mica_mode)"
	if [ ! "$mica_mode" = "ap" ]; then
		echo none > /sys/class/leds/mica\:wifi/trigger
		echo 1 > /sys/class/leds/mica\:wifi/brightness
		sleep 1
		echo "START WIFI AP" > /dev/console
		/usr/bin/wifi_mode ap
	fi
fi

return 0
