#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=10

start()
{
	# ugly hack alert - this is required to override the luci index.html file
	[ -f /www/index_7688.html ] && {
		cp /www/index_7688.html /www/index.html
		rm /www/index_7688.html
	}
	
	GPIO=19
    echo $GPIO > /sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio$GPIO/direction
    echo 1 > /sys/class/gpio/gpio$GPIO/value
    echo $GPIO > /sys/class/gpio/unexport
	
	WMODE=`uci get  wireless.radio0.mica_mode`
	
	case $WMODE in
    apsta)
        uci set wireless.radio0.mica_mode=apsta
        uci set wireless.sta.disabled=0
        uci set wireless.ap.disabled=0
        uci commit
        ;;
    sta)
        uci set wireless.radio0.mica_mode=sta
        uci set wireless.sta.disabled=0
        uci set wireless.ap.disabled=1
        uci commit
        ;;
    ap)	
        uci set wireless.radio0.mica_mode=ap
        uci set wireless.sta.disabled=1
        uci set wireless.ap.disabled=0
        uci commit
        ;;
    esac

	# sync the uboot envs wifi config with the uci wifi config
	SEQ=`fw_printenv -n wifi_seq`
	[ -n "${SEQ}" ] || return
	USEQ=`uci get wireless.ap.seq`
	[ -z "${USEQ}" ] && USEQ=0
	[ "${USEQ}" -lt "${SEQ}" ] && {
		SSID=`fw_printenv -n wifi_ssid`
		KEY=`fw_printenv -n wifi_key`
		[ -n "${SSID}" ] && uci set wireless.ap.ssid="${SSID}"
		[ -n "${KEY}" ] && {
			uci set wireless.ap.encryption='psk2'
			uci set wireless.ap.key="${KEY}"
		}
		uci set wireless.ap.seq="${SEQ}"
		uci commit wireless
	}
	
	
}
