#!/bin/sh

[ "$(uci get system.@system[-1].mica_firstboot)" = "1" ] && return 0

. /lib/ramips.sh
board=$(ramips_board_name)

[ "$board" = "mica7688" ] || {
	rm -f /etc/avahi/services/arduino.service
	return 0
}

