#!/bin/sh

. /lib/functions.sh
. /lib/functions/system.sh

sed -i "s/.*mica$//g" /etc/opkg/distfeeds.conf

wan_mac=$(mtd_get_mac_binary factory 4)

uci set network.wan.macaddr=$wan_mac
uci commit network

uci delete uhttpd.main.alias
uci commit uhttpd

WMODE=`uci get  wireless.radio0.mica_mode`
[ -z "${WMODE}" ] && {
	uci set wireless.radio0.mica_mode=ap
	uci set wireless.ap.disabled=0
	uci set wireless.sta.disabled=1
}

[ "$(uci get system.@system[-1].mica_firstboot)" = "1" ] && return 0

. /lib/ramips.sh
board=$(ramips_board_name)



uci set system.@system[-1].hostname="MiCa"
uci set wireless.radio0.disabled=0
uci set network.lan.ipaddr=192.168.76.1

SSID=`fw_printenv -n wifi_ssid`
KEY=`fw_printenv -n wifi_key`
SEQ=`fw_printenv -n wifi_seq`
[ -n "${SSID}" ] || { \
	MAC=$(dd bs=1 skip=7 count=3 if=/dev/mtd2 2>/dev/null | hexdump -v -n 3 -e '3/1 "%02X"')
	SSID=MiCa7688_${MAC}
}
[ -n "${SEQ}" ] || \
	SEQ=1
uci set wireless.ap.ssid="$SSID"
uci set wireless.ap.seq="$SEQ"

[ -n "${KEY}" ] && {
	uci set wireless.ap.encryption='psk2'
	uci set wireless.ap.key="$KEY"
}

uci set network.wan=interface
uci set network.wan.proto=dhcp
STAIFNAME=$(uci get wireless.sta.ifname)
uci set network.wan.ifname=$STAIFNAME

uci set mountd.mountd.path=/Media/

uci commit
return 0
