#!/bin/sh

LDR_VER=`grep UBOOTVER= /dev/mtd0 | cut -d= -f2`
[ -z "${LDR_VER}" ] && LDR_VER=0.1

uci set system.@system[0].firmware_version=v0.1
uci set system.@system[0].loader_version=v${LDR_VER}
uci set system.@system[0].mica_firstboot=1
uci commit system
