#!/bin/sh

LDR_VER=`grep UBOOTVER= /dev/mtd0 | cut -d= -f2`
[ -z "${LDR_VER}" ] && LDR_VER=0.1

uci set system.@system[0].firmware_version=v0.1
uci set system.@system[0].loader_version=v${LDR_VER}
uci set system.@system[0].mica_firstboot=1
uci commit system



cat <<"EOL" > /etc/banner
 __  __    _        _ _____ __    ___   ___  
 \ \/ /___| |_ __ _| |___  / /_  ( _ ) ( _ ) 
  \  // _ \ __/ _` | |  / / '_ \ / _ \ / _ \ 
  /  \  __/ || (_| | | / /| (_) | (_) | (_) |
 /_/\_\___|\__\__,_|_|/_/  \___/ \___/ \___/        lede-project.org
 
 ----------------------------------------------------------------
    Lede Reboot (17.01, mica.net)
 ----------------------------------------------------------------
EOL
