#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

# start after and stop before networking
START=20
STOP=89

USE_PROCD=1

service_triggers()
{
	procd_add_reload_trigger "micabridge"
}

start_service()
{
	[ "$(uci -q get micabridge.config.disabled)" = "1" ] && return 0
	procd_open_instance
	procd_set_param command "/sbin/micabridge"
	procd_set_param respawn
	procd_close_instance
}
